# Generated by Django 2.1.7 on 2019-03-22 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestfiles',
            old_name='session_id',
            new_name='csrf_id',
        ),
    ]
