# Generated by Django 2.1.7 on 2019-03-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190323_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='uuid',
            field=models.CharField(default='123', max_length=200),
            preserve_default=False,
        ),
    ]
