# Generated by Django 2.1.7 on 2019-03-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190325_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='uuid',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
