# Generated by Django 2.1.7 on 2019-03-25 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20190325_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfiles',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
