# Generated by Django 2.1.7 on 2019-03-25 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_requestfiles_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestfiles',
            options={'verbose_name_plural': 'Request files'},
        ),
    ]
