# Generated by Django 2.1.7 on 2019-03-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20190325_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfiles',
            name='tool_type',
            field=models.CharField(choices=[('merge', 'merge'), ('split', 'split')], default='merge', max_length=200),
            preserve_default=False,
        ),
    ]
