# Generated by Django 2.1.7 on 2019-03-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_requestfiles_tool_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='unq_dir_name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
